---
# Variables that can provide as extra vars
use_github_username: false  # Flag to indicate whether to use GitHub username
VPC_REGION: us-east-1  # AWS region for the VPC
GITHUB_USERNAME: "CHANGEME"  # GitHub username to be used
EC2_KEY_NAME: "my-default-key"  # Name of the EC2 key pair
LOCAL_USER_SSH_KEY: yes  # Flag to indicate whether to use local user SSH key

# Use inside the tasks
use_local_ssh_key: true  # Flag to indicate whether to use local SSH key
vpc_region: "{{ VPC_REGION }}"  # Variable for VPC region
github_username: "{{ GITHUB_USERNAME }}"  # Variable for GitHub username
local_user_ssh_key: "{{ LOCAL_USER_SSH_KEY }}"  # Variable for local user SSH key
ec2_key_name: "{{ EC2_KEY_NAME }}"  # Variable for EC2 key pair name

# Key used when deploying from Ansible Automation platform
use_aap_user_ssh_key: false  # Flag to indicate whether to use AAP user SSH key
aap_user_ssh_key: "{{ aap_user_ssh_key }}"  # Variable for AAP user SSH key
