---
# Variables that can provide as extra vars
VPC_NAME: test
VPC_REGION: us-east-1 # N.Virginia
EC2_INSTANCE_TYPE: t2.micro
EC2_KEY_NAME: "my-default-key"
EC2_SECURITY_GROUP_NAME: "test"
EC2_COUNT: 1
EC2_VOLUME_SIZE: 8
EC2_PRIVATE_SUBNET_ID: []
EC2_PUBLIC_SUBNET_ID: []

# Example of EC2_PUBLIC_SUBNET_ID
# EC2_PUBLIC_SUBNET_ID:
#   - "subnet-0c3e0b7b"
#   - "subnet-bf672ae6"


# Example of EC2_PRIVATE_SUBNET_ID
# EC2_PRIVATE_SUBNET_ID:
#   - "subnet-0c3e0b7b"
#   - "subnet-bf672ae6"
AMI_NAME: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207"
AMI_OWNER: "099720109477"

# Tags
ENVIRONMENT: test
SERVER_ROLE: test

# Use inside the tasks
vpc_name: "{{ VPC_NAME }}"
vpc_region: "{{ VPC_REGION }}"
ec2_instance_type: "{{ EC2_INSTANCE_TYPE }}"
ec2_key_name: "{{ EC2_KEY_NAME }}"
ec2_security_group_name: "{{ EC2_SECURITY_GROUP_NAME }}"
ec2_volume_size: "{{ EC2_VOLUME_SIZE }}"
ec2_count: "{{ EC2_COUNT }}"
ec2_subnet_id: "{{ EC2_SUBNET_ID }}"
deploy_public_ec2_instance: True
inventory_name: "[webserver]"

# Please don't change the variables below, until you know what you are doing
# Only Ubuntu distribution is supported
  
ami_name: "{{ AMI_NAME }}"
ami_owner: "{{ AMI_OWNER }}"
