---
- block:
    - name: "Grab key for {{ github_username }} user from github.com"
      uri:
        url: "https://github.com/{{ github_username }}.keys"
        return_content: yes
      register: github_key_result
      tags: [create-ec2key]

    - name: Creates an new ec2 key with mentioned name if not present
      ec2_key:
        region: "{{ vpc_region }}"
        name: "{{ ec2_key_name }}"
        key_material:  "{{ github_key_result.content }}"
      tags: [create-ec2key]

  when: 
    - github_username is defined
    - github_username | lower != 'no'
    - not local_user_ssh_key
    - not aap_user_ssh_key is defined

- block:
    - name: Find the current login user
      command: whoami
      register: login_user
      changed_when: no
      tags: [create-ec2key]

    - name: Set the Key location as fact
      set_fact: 
        ssh_key_location: "/home/{{ login_user.stdout }}/.ssh/id_rsa.pub"
      tags: [create-ec2key]

    - name: "Check that the SSH Key exists for {{ login_user.stdout }} user"
      stat:
        path: "{{ ssh_key_location }}"
      register: sshkey_result
      tags: [create-ec2key]

    - name: "Generating a new SSH key for {{ login_user.stdout }} user it does not exists already"
      user:
        name: "{{ login_user.stdout }}"
        generate_ssh_key: yes 
        ssh_key_bits: 2048
      when: sshkey_result.stat.exists == False
      tags: [create-ec2key]

    - name: Creates an new ec2 key with mentioned name if not present
      ec2_key:
        region: "{{ vpc_region }}"
        name: "{{ ec2_key_name }}"
        key_material:  "{{ lookup('file',  ssh_key_location ) }}"
      tags: [create-ec2key]
      
  when:
    - local_user_ssh_key
    - not github_username
    - not aap_user_ssh_key is defined

- block:
      - name: Create an EC2 key with aap_user_ssh_key
        ec2_key:
          region: "{{ vpc_region }}"
          name: "{{ ec2_key_name }}"
          key_material: "{{ aap_user_ssh_key }}"
        tags: [create-ec2key]

  when:
    - aap_user_ssh_key is defined
    - not local_user_ssh_key
    - not github_username
